---
env: "prd"
vpcs:
  - { name: "01" , cidr: "10.1.0.0/16" }
  - { name: "02" , cidr: "10.2.0.0/16" }
  - { name: "03" , cidr: "10.3.0.0/16" }
  - { name: "04" , cidr: "10.4.0.0/16" }
  - { name: "05" , cidr: "10.5.0.0/16" }
  - { name: "06" , cidr: "10.6.0.0/16" }
  - { name: "07" , cidr: "10.7.0.0/16" }
  - { name: "08" , cidr: "10.8.0.0/16" }
  - { name: "09" , cidr: "10.9.0.0/16" }
  - { name: "10" , cidr: "10.10.0.0/16" }
