AWSTemplateFormatVersion: 2010-09-09
Resources:
########################################
### EC2 InstanceName prd-windows-2019
########################################
  Ec2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06b2e1396e60a46be
      KeyName: kp_wai
      InstanceType: t2.medium
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile ConfigureRemotingForAnsible.ps1
          powershell -ExecutionPolicy RemoteSigned .\ConfigureRemotingForAnsible.ps1
          $admin = [ADSI]("WinNT://./administrator, user")
          $admin.SetPassword("Curry0000%")
          </powershell>
      Tags:
        - Key: env
          Value: prd
        - Key: os
          Value: windows
        - Key: version
          Value: 2019
        - Key: Name
          Value: prd-windows-2019
  EbsVolume1:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt Ec2Instance1.AvailabilityZone
      Size: 10
  MountPoint1:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: xvdf
      InstanceId: !Ref Ec2Instance1
      VolumeId: !Ref EbsVolume1
    DependsOn:
      - Ec2Instance1
      - EbsVolume1
