---
- name: upgrade all packages
  apt:
    update_cache: true

- name: update all packages
  apt:
    upgrade: dist
    update_cache: true

- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - aptitude
      - python3-pip
      - python3-setuptools

- name: install psutil
  pip:
    name: psutil
