---
- name: Creates a data migration services endpoint - source
  dms_endpoint:
    state: "{{ state|default('present') }}"
    endpointidentifier: 'source'
    endpointtype: source
    enginename: mysql
    username: mysqluser1
    password: mysqlpass1
    servername: mysql.domain.com
    port: 3306
    databasename: 'sourcedb'
  register: res_source

- name: EndpointArn is output when there is a change in the task - source
  debug:
    var: res_source.msg.Endpoint.EndpointArn
  when: res_source.changed

- name: Creates a data migration services endpoint - target
  dms_endpoint:
    state: "{{ state|default('present') }}"
    endpointidentifier: 'target'
    endpointtype: target
    enginename: aurora
    username: mysqluser1
    password: mysqlpass1
    servername: aurora.domain.com
    port: 3306
    databasename: 'targetdb'
  register: res_target

- name: EndpointArn is output when there is a change in the task - target
  debug:
    var: res_target.msg.Endpoint.EndpointArn
  when: res_target.changed
