---
- name: set timezone
  win_timezone:
    timezone: Tokyo Standard Time

- name: change region
  win_region:
    location: 122
    format: ja-JP
    unicode_language: ja-JP
  register: result

- name: reboot
  win_reboot:
  when: result.restart_required
