---
- name: CloudFormation test
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - name: cfn_create
      vars:
        cfn_var_name: "{{ ec2s }}"
        cfn_yml_name: "win"
      tags: [ 'cfn' , 'ec2' , 'win' ]
