---
- name: CloudFormation Windows EC2
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - name: cfn_create
      vars:
        - { cfn_var_name: "{{ ec2s.record }}" , task_yml_name: "win" , cfn_yml_name: "ec2_win" }
      tags: [ 'ec2' , 'windows' ]
