---
# AWS
ec2s:
  windows_stack:
    - stack_name: "{{ env }}-ec2-windows"
      jinja2_name: ec2.jinja2
      linedata:
        - name: "{{ env }}-windows-2019"
          keypair: kp_wai
          os: windows
          version: 2019
          imageid: ami-04b47b75a5897bac8
          instance_type: t2.medium
#        - name: "{{ env }}-windows-2016"
#          keypair: kp_wai
#          os: windows
#          version: 2016
#          imageid: ami-00ca08896c37c01d0
#          instance_type: t2.medium
#        - name: "{{ env }}-windows-2012R2"
#          keypair: kp_wai
#          os: windows
#          version: 2012R2
#          imageid: ami-01847ac7578ef1007
#          instance_type: t2.medium
  linux_stack:
    - stack_name: "{{ env }}-ec2-linux"
      jinja2_name: ec2.jinja2
      linedata:
        - name: "{{ env }}-linux-ubuntu-1804"
          keypair: keypair_cloud9
          os: linux
          imageid: ami-0eb48a19a8d81e20b
          instance_type: t2.micro
