---
# WinRM setting
ansible_user: administrator
ansible_password: "{{ password }}"
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

# Windows vars
win_user:
  - username: "user1"
    password: "P@ssw0rd"
  - username: "user2"
    password: "P@ssw0rd"
  - username: "user3"
    password: "P@ssw0rd"
