---
- name: retrieve disc information
  win_disk_facts:

- name: abort when the disk number does not exist
  fail:
    msg: "Disk does not exist. ( disk_number = {{ disk_number }} ) "
  when: ansible_disks[disk_number] is undefined

- name: initialize disk
  win_shell: "Initialize-Disk -Number {{ disk_number }}"
  when: ansible_disks[disk_number].guid is none

- name: create partition
  win_partition:
    drive_letter: "{{ drive_letter }}"
    partition_size: -1
    disk_number: "{{ disk_number }}"
  when: ansible_disks[disk_number].guid is none

- name: format disk
  win_format:
    drive_letter: "{{ drive_letter }}"
    file_system: NTFS
    new_label: Formatted
    full: True
  when: ansible_disks[disk_number].guid is none
