---
- name: cfn template generate
  template:
    src: "{{ jinja2_path }}/{{ item.jinja2_name }}"
    dest: "{{ stack_path }}/{{ item.name }}.yaml"

- name: get cloudformation info
  cloudformation_facts:
    stack_name: "{{ item.name }}"
  register: res

- name: set cloudformation info
  set_fact:
    cfn_state: "{{ ansible_facts['cloudformation'][ item.name ]['stack_description']['stack_status'] }}"
  when: ansible_facts['cloudformation'][ item.name ] is defined

- name: remove a cloudformation stack
  cloudformation:
    stack_name: "{{ item.name }}"
    state: "absent"
  when: cfn_state is defined and cfn_state == "CREATE_FAILED"

- name: create a temporary keypair
  ec2_key:
    name: "{{ keypair }}"
    state: "present"
  changed_when: false
  when: state=="present"

- name: create a cloudformation stack
  cloudformation:
    stack_name: "{{ item.name }}"
    state: "{{ state }}"
    region: "{{ region }}"
    disable_rollback: true
    template: "{{ stack_path }}/{{ item.name }}.yaml"
    tags:
      Stack: "ansible-cloudformation"
  register: res

- name: sleep 30
  wait_for:
    sleep: 30
  when: res.changed and state=="present"

- name: remove a temporary keypair
  ec2_key:
    name: "{{ keypair }}"
    state: "absent"
  changed_when: false
  when: state=="present"
