---
- name: create a cloudformation stack
  cloudformation:
    stack_name: "{{ item.name }}"
    state: "{{ state }}"
    region: "{{ region }}"
    disable_rollback: true
    template: "cfn/template/{{ cfn_yml_name }}.yaml"
    template_parameters:
      CidrBlock: "{{ item.cidr }}"
      TagEnv: "{{ env }}"
    tags:
      Stack: "ansible-cloudformation"
