---
- name: create directory
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ download_dir }}"
    - "{{ extract_dir }}"

- name: download powershell 5
  win_get_url:
    url: https://go.microsoft.com/fwlink/?linkid=839516
    dest: "{{ download_fullpath }}"

- name: extract powershell 5
  raw: "wusa.exe {{ download_fullpath }} /extract:{{ extract_dir }}"

- name: install powershell 5
  raw: "pkgmgr.exe /n:{{ install_fullpath }} /norestart"

- name: reboot
  win_reboot:
