---
# AWS
ec2s:
  record:
    - name: "{{ env }}-ec2-01"
      os: "windows"
      version: "2019"
      imageid: ami-068d819e778ed76e6
      instance_type: t2.medium
      jinja2_name: ec2_win.jinja2
