AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  TagEnv: 
    Type: String
    Description: TagEnv.
  TagOs: 
    Type: String
    Description: TagOs.
  TagVerion: 
    Type: String
    Description: TagVerion.
  Keypair: 
    Type: String
    Description: Keypair.
Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-065bdc46039060415"
      KeyName: !Ref Keypair
      InstanceType: "t2.medium"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile ConfigureRemotingForAnsible.ps1
          powershell -ExecutionPolicy RemoteSigned .\ConfigureRemotingForAnsible.ps1
          $admin = [ADSI]("WinNT://./administrator, user")
          $admin.SetPassword("Curry0000%")
          </powershell>
      Tags:
        - Key: "env"
          Value: !Ref TagEnv
        - Key: "os"
          Value: !Ref TagOs
        - Key: "version"
          Value: !Ref TagVerion
