---
- name: set timezone
  win_timezone:
    timezone: Tokyo Standard Time

- name: change region
  win_region:
    location: 122
    format: ja-JP
    unicode_language: ja-JP
  register: result

- name: reboot
  win_reboot:
  when: result.restart_required

- name: wait for
  win_wait_for:
    port: 3389
    delay: 60
  when: result.restart_required
