---
- name: create a cloudformation stack
  cloudformation:
    stack_name: "VPC-{{ env }}-{{ item.name }}"
    state: "{{ state }}"
    region: "{{ region }}"
    disable_rollback: true
    template: "cfn/template/vpc.yaml"
    template_parameters:
      CidrBlock: "{{ item.cidr }}"
      TagEnv: "{{ env }}"
    tags:
      Stack: "ansible-cloudformation"
  with_items: "{{ vpcs }}"
