---
- name: get cloudformation info
  cloudformation_facts:
    stack_name: "{{ item.name }}"
  register: res

- set_fact:
    cfn_state: "{{ ansible_facts['cloudformation'][ item.name ]['stack_description']['stack_status']|detaults[""] }}"

- name: remove a cloudformation stack
  cloudformation:
    stack_name: "{{ item.name }}"
    state: "absent"
  when: cfn_state == "CREATE_FAILED"

- name: create a cloudformation stack
  cloudformation:
    stack_name: "{{ item.name }}"
    state: "{{ state }}"
    region: "{{ region }}"
    disable_rollback: true
    template: "cfn/template/vpc.yaml"
    template_parameters:
      CidrBlock: "{{ item.cidr }}"
      TagEnv: "{{ env }}"
    tags:
      Stack: "ansible-cloudformation"
