---
- name: CloudFormation Windows Deploy
  hosts: all
  gather_facts: true
  roles:
    - name: win_common
      tags:
        - windows
        - common

    - name: win_update
      tags:
        - windows
        - update
