AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  CidrBlock: 
    Type: String
    Description: CidrBlock.
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref CidrBlock
